version: "3.8"

services:

  mongodb:
    image: mongo:8
    container_name: employee-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db


  backend:
    build: ./backend
    container_name: employee-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      PORT: 5000
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/employee_management?authSource=admin
      JWT_SECRET: employee_secret_key


  frontend:
    build: ./frontend
    container_name: employee-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend


volumes:
  mongo-data:
