apiVersion: v1
kind: Service
metadata:
  name: enterprise-backend
spec:
  selector:
    app: enterprise-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort
