apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-backend
  template:
    metadata:
      labels:
        app: enterprise-backend
    spec:
      containers:
        - name: backend
          image: enterprise-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: enterprise-backend-secret
                  key: MONGO_URI
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
