name: Employee Management CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Backend Check
        working-directory: backend
        run: node server.js


  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Frontend Build
        working-directory: frontend
        run: npm run build


  docker-build:
    name: Docker Build Verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker compose build
