name: Employee Management Platform CI/CD

on:
  workflow_run:
    workflows: ["Employee Management CI-CD"]
    types:
      - completed

jobs:

  build-and-test:

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24


      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install


      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install


      - name: Build Frontend
        working-directory: frontend
        run: npm run build


      - name: Validate Docker Compose
        run: docker compose config


      - name: Build Docker Images
        run: docker compose build


  deploy-to-ec2:

    needs: build-and-test

    runs-on: ubuntu-latest

    steps:

      - name: Deploy Application to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            cd ~/employee-management

            git pull

            docker pull pradeepdevops5281/employee-management-backend:latest

            docker pull pradeepdevops5281/employee-management-frontend:latest

            docker compose down

            docker compose up -d

            docker ps

            echo "Running deployment health check..."

            ./scripts/health-check.sh

            echo "Deployment health check passed"
